name: Build and Push Docker Image (Dev)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el código fuente del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # Paso 3: Construir la imagen Docker usando Dockerfile.dev
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile.dev -t igrowker/i004-crewland-front-dev-image:latest .

      # Paso 4: Publicar la imagen en Docker Hub
      - name: Push Docker Image
        run: |
          docker push igrowker/i004-crewland-front-dev-image:latest
